baseURL: https://chandrimatoliaportfolio.netlify.app
languageCode: en-us
title: Portfolio Website for Chandrima Tolia
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: LET'S GET ROLLING!
    subtitle: |- AND WELCOME TO MY PORTFOLIO WEBSITE! 
      
    title: Namaste, I'm Chandrima Tolia
  blog: {}
  contact:
    address:
      - city: London, NW1 4SA
        country: United Kingdom
        street: Regent's Park
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: ctolia.mam2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (+44) 07577 550633
        title: Phone
  custom_css: []
  custom_js: []
  description: love yourself <3
  error404:
    heading: Ooops! Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: 2021 Chandrima Tolia
    enable: yes
   # quicklinks:
     # - alt: HTML5 UP
     #   text: 'Design: '
    #    url: https://www.html5up.net
    social:
      #- icon: fa-twitter
      #  label: Twitter
      #  url: https://www.twitter.com
     # - icon: fa-facebook
     #  label: Facebook
     #   url: https://www.facebook.com
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/chandrimatolia_/
      - icon: fa-github
        label: GitHub
        url: https://github.com/chandrimatolia
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/chandrima-tolia/
  image: ''
  name: Chandrima Tolia
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
     # - name: Blogs
     #   url: blogs
     # - name: Generic Blog
      #  url: blogs/ipsum
     # - name: Elements
     #   url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: chandrima.jpg
        subtitle: There's more to me than meets the eye! :)
        title: About Me
        url: blogs/chandrima
      - image: returns.jpg
        subtitle: Performance Analysis of Apple (AAPL), Walt Disney (DIS), Domino's Pizza (DPZ), Abercrombie & Fitch Co. (ANF), Tesla (TSLA), 
Exxon Mobil Corporation (XOM), and the S&P500 Exchange Traded Fund (SPY) via Stock Returns
        title: Returns on Financial Stocks
        url: blogs/returns
      - image: brexit.png
        subtitle: Dive deeper into Brexit Vote Analysis and how political affiliations translated to Brexit Voting?
        title: Brexit Vote Analysis
        url: blogs/brexit
      - image: gdp.jpg
        subtitle: Revisiting Gapminder dataset and Analysing GDP components over time and among countries
        title: Gapminder Revisited + GDP Evolution over time!
        url: blogs/gdp
      - image: omega.jpg
        subtitle: Gender Pay Gap Analysis at Omega PLC
        title: Omega Group plc- Pay Discrimination
        url: blogs/omega
      - image: imdb.png
        subtitle: Movie Analysis + Difference in Ratings between directors Spielberg and Burton
        title: IMDB Movies + Ratings Analysis
        url: blogs/imdb
  two:
    buttonText: Download Resume!
    enable: yes
    #subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
    #  \n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \n    Pellentesque
    #  condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
    # pellentesque lorem ipsum dolor. \n    Nullam et orci eu lorem consequat tincidunt.
    #  Vivamus et sagittis libero.\n    Mauris aliquet magna magna sed nunc rhoncus
    #  amet pharetra et feugiat tempus."
    title: My Resume
    url: https://drive.google.com/file/d/11L0HY-A6jrkzWmmfWNhBGNGM27GBBYV-/view?usp=sharing
